/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc3475SolSol from "./ERC3475.sol.sol";
export type { erc3475SolSol };
export type { ERC3475 } from "./ERC3475";
export type { IERC3475 } from "./IERC3475";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { ERC3475 } from "./ERC3475.sol.sol/ERC3475";
export { ERC3475__factory } from "./factories/ERC3475.sol.sol/ERC3475__factory";
export { IERC3475__factory } from "./factories/IERC3475__factory";
export { Lock__factory } from "./factories/Lock__factory";
